# Numpy assignment
- Different tasks will be detailed by comments or text.
- For further reference and resources, it's advised to check out the NumPy documentation.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a= np.array( [5,1,2] )

# Create a 2-dimensional NumPy array using np.array()
b = np.array( [ [6, 1.2, 5],[2.0, 7, 8.2] ] )

In [3]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
print( "Shape: ", a.shape )
print("Number of dimensions: ", a.ndim)
print("Size: ", a.size)
print("Type: ", a.dtype)

Shape:  (3,)
Number of dimensions:  1
Size:  3
Type:  int32


In [4]:
# Attributes of 2-dimensional array
print( "Shape: ",b.shape )
print("Number of dimensions: ", b.ndim)
print("Size: ", b.size)
print("Type: ", b.dtype)

Shape:  (2, 3)
Number of dimensions:  2
Size:  6
Type:  float64


In [5]:
# Create an array of shape (5, 5) with only ones
o= np.ones( (5,5), np.int64)
o

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [6]:
# Create an array of shape (3, 3, 5) with only zeros
z= np.zeros( (3,3,5), np.int64)
z

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int64)

In [7]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a1=  np.random.randint(0, 10, (7,2), np.int64 )
a1

array([[3, 5],
       [6, 2],
       [5, 3],
       [3, 0],
       [6, 4],
       [8, 6],
       [6, 1]], dtype=int64)

In [8]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a2=np.random.rand( 3,5 )
a2

array([[0.89785653, 0.4572419 , 0.9073584 , 0.93888905, 0.65828944],
       [0.95935244, 0.11330799, 0.63160771, 0.92068685, 0.91065819],
       [0.18173001, 0.4110939 , 0.85281101, 0.69716524, 0.25304814]])

In [9]:
# Create an array of normally distributed random numbers
a3= np.random.randn(5)
a3

array([ 0.94758519, -1.26243023,  1.28263417,  0.31207396,  0.0270566 ])

In [10]:
# Set the random seed to 42
np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
a4=np.random.randint(10, size=(4, 6))
a4

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [11]:
# Copy the code from the cell above and run it again
np.random.seed(42)
a5= np.random.rand(4,6)
a5

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452],
       [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
        0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
        0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
        0.36636184]])

In [12]:
# Find the 0'th index of the latest array you created
print(a5[0][0])

0.3745401188473625


In [13]:
# Get the first 2 rows of latest array you created
a5[0:2]

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452],
       [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
        0.96990985]])

In [14]:
# Get the first 2 values of the first 2 rows of the latest array
a5[:2,:2]

array([[0.37454012, 0.95071431],
       [0.05808361, 0.86617615]])

In [15]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
b1 = np.random.randint(0, 10, (3,5), np.int64)
b2 = np.ones( (3,5), np.int64)


In [16]:
b1

array([[2, 6, 3, 8, 2],
       [4, 2, 6, 4, 8],
       [6, 1, 3, 8, 1]], dtype=int64)

In [17]:
b2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [18]:
# Add the two arrays together
add=b1+b2
add

array([[3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9],
       [7, 2, 4, 9, 2]], dtype=int64)

In [19]:
# Create another array of ones of shape (5, 3)
b3 = np.ones( (5,3), np.int64 )
b3

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [20]:
# Try add the array of ones and the other most recent array together # You can anticipate an error
add+b3

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [21]:
# Do the same operation you just did but this time with a transpose on one array
b4=add+b3.T
b4

array([[ 4,  8,  5, 10,  4],
       [ 6,  4,  8,  6, 10],
       [ 8,  3,  5, 10,  3]], dtype=int64)

In [22]:
# Take the latest array to the power of 2 using the python way
b4**2

array([[ 16,  64,  25, 100,  16],
       [ 36,  16,  64,  36, 100],
       [ 64,   9,  25, 100,   9]], dtype=int64)

In [23]:
# Do the same thing with numpy way
np.square(b4)

array([[ 16,  64,  25, 100,  16],
       [ 36,  16,  64,  36, 100],
       [ 64,   9,  25, 100,   9]], dtype=int64)

In [24]:
# Find the mean, min, max, standard deviation, variance of the latest array using np.mean()
mean = np.mean(b4)
max = np.max(b4)
min = np.min(b4)
std = np.std(b4)
var = np.var(b4)
print(mean)
print(max)
print(min)
print(std)
print(var)

6.266666666666667
10
3
2.462158041682585
6.062222222222222


In [26]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
c1 = np.random.randint(0,10, (3,3), np.int64)
c2 = np.random.randint(0,10, (3,2), np.int64)
print(c1)
print(c2)

[[5 5 9]
 [3 5 1]
 [9 1 9]]
[[3 7]
 [6 8]
 [7 4]]


In [27]:
# Perform a dot product on the two newest arrays you created
dot = np.dot(c1,c2)
print(dot)

[[108 111]
 [ 46  65]
 [ 96 107]]


In [28]:
# Create two arrays of random integers between 0 to 10 both of size (4, 3)
d1 = np.random.randint(0,10, (4,3), np.int64)
d2 = np.random.randint(0,10, (4,3), np.int64)

In [29]:
d1

array([[1, 4, 7],
       [9, 8, 8],
       [0, 8, 6],
       [8, 7, 0]], dtype=int64)

In [30]:
d2

array([[7, 7, 2],
       [0, 7, 2],
       [2, 0, 4],
       [9, 6, 9]], dtype=int64)

In [31]:
# Perform a hadamard product on the two newest arrays you created
hadm=d1*d2
hadm

array([[ 7, 28, 14],
       [ 0, 56, 16],
       [ 0,  0, 24],
       [72, 42,  0]], dtype=int64)

In [32]:
# Perform a dot product on the two newest arrays you created # Error anticipated
np.dot(d1, d2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [33]:
# Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both
np.dot(d1.T, d2)

array([[ 79, 118,  92],
       [107, 126, 119],
       [ 61, 105,  54]], dtype=int64)

In [34]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
e1 = np.random.randint(0,10, 5)
e2 = np.random.randint(0,10, 5)

In [35]:
e1

array([8, 6, 8, 7, 1])

In [36]:
e2

array([0, 6, 6, 7, 4])

In [37]:
# Compare the two arrays with '>', '<=' and '==' 
e1 > e2

array([ True, False,  True, False, False])

In [38]:
e1 <= e2

array([False,  True, False,  True,  True])

In [39]:
e1 == e2

array([False,  True, False,  True, False])

In [40]:
# Sort one of the arrays you just created in ascending order
np.sort(e2)

array([0, 4, 6, 6, 7])

In [41]:
# Sort the indexes of one of the arrays you just created
np.argsort(e2)

array([0, 4, 1, 2, 3], dtype=int64)

In [42]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(e2)

3

In [43]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [46]:
# Find the indexes with the maximum values down the verticial axis of one of the arrays you created
np.argmax(d1, axis=1)

array([2, 0, 1, 0], dtype=int64)

In [45]:
# Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
np.argmin(d1, axis=0)

array([2, 0, 3], dtype=int64)